# Generated by Django 6.0.1 on 2026-04-19 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=50)),
                ('cgpa', models.CharField(blank=True, max_length=20)),
                ('label', models.CharField(blank=True, help_text="e.g. 'Online Degree'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(default='Present', max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sankar K', max_length=100)),
                ('title', models.CharField(default='Backend Dev.', max_length=100)),
                ('tagline', models.CharField(default='Available for Backend Roles', max_length=200)),
                ('tech_stack', models.CharField(default='Python · Django · DRF · PostgreSQL · Redis · Celery · OAuth · JWT', max_length=300)),
                ('bio', models.TextField(default='I build backend systems that scale.')),
                ('location', models.CharField(default='Chennai, Tamil Nadu, India', max_length=100)),
                ('email', models.EmailField(default='kaliyannansankar1999@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91-8754844723', max_length=20)),
                ('linkedin_url', models.URLField(default='https://www.linkedin.com/in/sankar-django-dev')),
                ('github_url', models.URLField(default='https://github.com/Sankar26-py')),
                ('github_project_url', models.URLField(default='https://github.com/Sankar26-py/foodOnline')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('is_open_to_work', models.BooleanField(default=True)),
                ('footer_text', models.CharField(default='Designed & built — Sankar K © 2026 · Python Django Developer · Chennai, India', max_length=200)),
                ('years_exp', models.CharField(default='3.6+', max_length=10)),
                ('perf_gain', models.CharField(default='30%', max_length=10)),
                ('automation_gain', models.CharField(default='40%', max_length=10)),
                ('api_count', models.CharField(default='5+', max_length=10)),
                ('cgpa', models.CharField(default='9.54', max_length=10)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('github_url', models.URLField(blank=True)),
                ('label', models.CharField(blank=True, help_text="e.g. 'GitHub →' or 'SRMIST Thesis'", max_length=50)),
                ('is_external', models.BooleanField(default=True, help_text='If False, shows as muted label (no link)')),
                ('tags', models.CharField(help_text='Comma-separated: Django, DRF, PostgreSQL', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='portfolio_app.experience')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='portfolio_app.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🐍', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='portfolio_app.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_highlights', to='portfolio_app.profile')),
            ],
            options={
                'verbose_name': 'About Highlight',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio_app.skillcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
